name: Fealty CD

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  Packer:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    name: Build Infrastructure | Packer

    steps:
      - name: Packer Setup
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: deploy/packer

      - name: Build Image
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: deploy/packer
        env:
          PACKER_LOG: 1

      - name: Upload Manifests
        uses: actions/upload-artifact@v2
        with:
          name: packer-manifests
          path: deploy/packer/*-manifest.json

  Terraform:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    name: Deploy Infrastructure | Terraform

    steps:
      - name: Checkout
        if: github.event.pull_request.merged
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Download Packer Manifests
        uses: actions/download-artifact@v2
        with:
          working-directory: deploy/packer

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Deploy
        run: terraform apply -auto-approve

      - name: Version
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-bump-patch-version: true
          changelog-generator-opt: "emojis=true"
          changelog-file: true
          allow-initial-development-versions: true
