name: Fealty CD

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  packer:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    name: Build Infrastructure

    steps:
      - name: Packer Setup
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: deploy/packer

      - name: Packer Validate
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: deploy/packer
      
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: deploy/packer
        env:
          PACKER_LOG: 1

  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    name: Deploy Infrastructure

    steps:
      - name: Checkout
        if: github.event.pull_request.merged
        uses: actions/checkout@v2
        with:
          ref: master
        
      - name: Download Binary
        uses: actions/download-artifact@master
        with:
          name: fealty-binary
          path: artifacts/fealty
      
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Deploy
        run: terraform apply -auto-approve

      - name: Version
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-bump-patch-version: true
          changelog-generator-opt: "emojis=true"
          changelog-file: true
          allow-initial-development-versions: true