name: Fealty CD

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - name: Checkout
        if: github.event.pull_request.merged
        uses: actions/checkout@v2
        with:
          ref: master
        
      - name: Download Binary
        uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
      
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Deploy
        run: terraform apply -auto-approve

      - name: Version
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-bump-patch-version: true
          changelog-generator-opt: "emojis=true"
          changelog-file: true
          allow-initial-development-versions: true