name: Cert Renewal

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1" # 2AM Every Week on Monday

jobs:
  CertRenewal:
      runs-on: ubuntu-latest
      name: Cert Renewal
      env:
        TF_VAR_LINODE_TOKEN: "${{ secrets.LINODE_TOKEN }}"
        TF_VAR_DOMAIN: "${{ secrets.DOMAIN }}"
        AWS_ACCESS_KEY_ID: "${{ secrets.OBJECT_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.OBJECT_SECRET_KEY }}"

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            ref: main

        # Only has 90 day retention so we need a way to
        # get these from Object Storage as well ideally
        - name: Download App Manifest
          uses: actions/download-artifact@v2
          with:
            name: app-manifest
            path: deploy/packer/

        - name: Download DB Manifest
          uses: actions/download-artifact@v2
          with:
            name: db-manifest
            path: deploy/packer/

        - name: Setup
          uses: hashicorp/setup-terraform@v1

        - name: Init
          id: init
          run: terraform -chdir=deploy init

        - name: Refresh
          id: refresh
          run: terraform -chdir=deploy refresh

        - name: Renew Cert
          id: renew
          run: terraform -chdir=deploy apply -target=acme_certificate.certificate -auto-approve
