name: Fealty Infrastructure Destroyer

on:
  workflow_dispatch:

jobs:
  Terraform_Destroy:
      runs-on: ubuntu-latest
      name: Destroy Infrastructure
      env:
        TF_VAR_LINODE_TOKEN: "${{ secrets.LINODE_TOKEN }}"
        AWS_ACCESS_KEY_ID: "${{ secrets.OBJECT_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.OBJECT_SECRET_KEY }}"
        TF_VAR_DOMAIN: "${{ secrets.DOMAIN }}"

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            ref: main

        - name: Setup
          uses: hashicorp/setup-terraform@v1

        - name: Init
          id: init
          run: terraform -chdir=deploy init

        - name: Destroy
          run: terraform -chdir=deploy destroy -auto-approve
